version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - xtermi2
    ignore:
      - dependency-name: de.ruedigermoeller:fst
        versions:
          - ">= 3.a, < 4"
      - dependency-name: io.vertx:*
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
