name: 'Test Report'
on:
  workflow_run:
    # runs after Java CI workflow
    workflows: [ 'Java CI' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit Tests
          path: '**/*.xml'
          reporter: java-junit